--liquibase formatted sql
--changeset 0008:1
create table organization
(
    org_id      integer primary key generated by default as identity,

    name        text not null,
    description text,

    coordinates_lon float4,
    coordinates_lat float4
);

--changeset 0008:2
create table organization_tags
(
    org_id integer references organization on delete cascade,
    tag_id integer references filter_tag,
    primary key (org_id, tag_id)
);

--changeset 0008:3
create table project
(
    project_id  integer primary key generated by default as identity,
    org_id      integer references organization on delete cascade,

    title       text,
    description text,

    coordinates_lon float,
    coordinates_lat float
);

--changeset 0008:4
create table project_tags
(
    project_id integer references project on delete cascade,
    tag_id     integer references filter_tag,
    primary key (project_id, tag_id)
);

--changeset 0008:5
create table region
(
    region_id   integer primary key generated by default as identity,

    name        text,
    description text,

    coordinates_lon float,
    coordinates_lat float
);
