--liquibase formatted sql
--changeset 0011:1
create table organization
(
    org_id      integer primary key generated by default as identity,

    name        text not null,
    description text not null,
    founding_year integer not null,

    members integer,

    website_url text,
    donation_url text,

    coordinates_lon float4,
    coordinates_lat float4
    /* images and logo maybe added later*/
);

--changeset 0011:2
create table organization_tags
(
    org_id integer references organization on delete cascade,
    tag_id integer references filter_tag,
    primary key (org_id, tag_id)
);

--changeset 0011:3
create table project
(
    project_id  integer primary key generated by default as identity,
    org_id      integer references organization on delete cascade,

    title       text not null,
    description text not null,

    date_from date,
    date_to date,

    website_url text,
    donation_url text,

    coordinates_lon float,
    coordinates_lat float
);

--changeset 0011:4
create table project_tags
(
    project_id integer references project on delete cascade,
    tag_id     integer references filter_tag,
    primary key (project_id, tag_id)
);
