services:
  sapling-squad-keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "5555:8080"
    command: start-dev --import-realm
    volumes:
      - ./initrealms:/opt/keycloak/data/import
