package saplingsquad.api.service

import kotlinx.coroutines.flow.Flow
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken
import org.springframework.stereotype.Service
import org.springframework.web.server.ResponseStatusException
import saplingsquad.api.OrganizationApiDelegate
import saplingsquad.api.models.*
import saplingsquad.api.toLonLatList
import saplingsquad.persistence.OrganizationRegisterResult
import saplingsquad.persistence.OrganizationsRepository
import saplingsquad.persistence.tables.CoordinatesEmbedded
import saplingsquad.persistence.tables.OrganizationEntity
import saplingsquad.utils.asHttpOkResponse

@Service
class OrganizationApiService(private val organizationsRepository: OrganizationsRepository) : OrganizationApiDelegate {
    override suspend fun registerOrganization(
        orgaToken: JwtAuthenticationToken,
        organization: Organization
    ): ResponseEntity<Int> {
        val result = organizationsRepository.tryRegisterOrganization(
            orgaToken.token.subject, OrganizationEntity(
                orgId = 0, // Will be autogenerated (i.e. ignored by komapper)
                name = organization.name,
                description = organization.description,
                foundingYear = organization.foundingYear,
                memberCount = organization.memberCount,
                websiteUrl = organization.webpageUrl,
                donationUrl = organization.donatePageUrl,
                coordinates = organization.coordinates.let {
                    CoordinatesEmbedded(
                        it[0].toDouble(),
                        it[1].toDouble()
                    )
                }
            )
        )
        return when (result) {
            is OrganizationRegisterResult.AlreadyRegistered ->
                throw ResponseStatusException(
                    HttpStatus.FORBIDDEN,
                    "Already registered an organization with this account"
                )

            is OrganizationRegisterResult.Success -> ResponseEntity.ok()
                .contentType(MediaType.TEXT_PLAIN)
                .body(result.id)
        }
    }

    override suspend fun getOrganization(orgaToken: JwtAuthenticationToken): ResponseEntity<GetOrganizationDetails200Response> {
        return organizationsRepository
            .readOrganizationOfAccount(orgaToken.token.subject)!!
            .let {
                GetOrganizationDetails200Response(
                    orgaId = it.orgId,
                    name = it.name,
                    description = it.description,
                    foundingYear = it.foundingYear,
                    memberCount = it.memberCount,
                    webpageUrl = it.websiteUrl,
                    donatePageUrl = it.donationUrl,
                    imageUrls = emptyList(), //TODO maybe implement images sometime
                    coordinates = it.coordinates.toLonLatList()
                )
            }
            .asHttpOkResponse()
    }

    override suspend fun updateOrganization(
        orgaToken: JwtAuthenticationToken,
        organizationDescriptions: GetOrganizationDetails200Response?
    ): ResponseEntity<Unit> {
        TODO("Not yet implemented")
    }

    override suspend fun createProject(orgaToken: JwtAuthenticationToken, project: Project?): ResponseEntity<Int> {
        TODO("Not yet implemented")
    }

    override fun getProjectForOrga(orgaToken: JwtAuthenticationToken): ResponseEntity<Flow<GetProjectForOrga200ResponseInner>> {
        TODO("Not yet implemented")
    }

    override suspend fun updateProject(
        orgaToken: JwtAuthenticationToken,
        projectDescriptions: GetProject200Response?
    ): ResponseEntity<Unit> {
        TODO("Not yet implemented")
    }

    override suspend fun deleteProject(orgaToken: JwtAuthenticationToken, projectId: Int): ResponseEntity<Unit> {
        TODO("Not yet implemented")
    }
}
