services:
  sapling-squad-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sapling-squad
      POSTGRES_PASSWORD: sapling-squad
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: sapling@example.com
      PGADMIN_DEFAULT_PASSWORD: squad
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - sapling-squad-db

volumes:
  postgres_data:
    name: sapsquad-postgres-data
  pgadmin_data:
    name: sapsquad-squad-pgadmin-data