create table filter_tag
(
    id   integer primary key generated by default as identity,
    name text not null
);

create table frage
(
    id    integer primary key generated by default as identity,
    frage text not null,
    tag   integer references filter_tag
);
