create table filter_tag
(
    id   integer primary key generated by default as identity,
    name text not null
);

create table question
(
    id    integer primary key generated by default as identity,
    question text not null,
    image_url text,
    tag   integer references filter_tag
);
