@startuml DomainModel

	!theme crt-amber
	skinparam ArrowFontColor #FFB000
	hide circle
	hide empty methods
	hide empty attributes

	!pragma layout elk

	skinparam nodesep 200
	skinparam ranksep 200
	skinparam minClassWidth 100

	class Nutzer

	class Karte
	Karte "1" --> "1" Nutzer: ist für

	class Pin
	Pin : lat
	Pin : long
	Pin "*" --> "1" Karte : ist auf

	class Projekt
	Projekt : name
	Projekt : beschreibung
	Projekt "1" --> "1" Pin : angezeigt als

	class Verein
	Verein : name
	Verein : beschreibung
	Verein "1" --> "1" Pin : angezeigt als
	Verein "1" --> "*" Projekt : hat

	class Region
	Region : name
	Region : beschreibung
	Region "1" --> "1" Pin : angezeigt als

	class Frage
	Frage "*" --> "1" Filter : setzt

	class Filter
	Filter "1" --> "*" Projekt : filtert
	Filter "1" --> "*" Verein : filtert

@enduml
