spring.application.name: backend
server.port: ${port:9000}

spring:
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}"
    username: ${DB_USER:sapling-squad}
    password: ${DB_PASSWORD:sapling-squad}
appconfig:
  openapi:
    spec: "static/api/spec.yaml" # local path to spec.yaml
  allow-wildcard-cors: true
  resources-url-path: "api/rsc/"

springdoc:
  swagger-ui:
    url: "api/spec.yaml" # served path to spec.yaml
  enable-default-api-docs: false
