spring.application.name: backend
server.port: ${port:9000}

spring:
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}"
    username: ${DB_USER:sapling-squad}
    password: ${DB_PASSWORD:sapling-squad}
appconfig:
  openapi:
    spec: "static/api/spec.yaml"
  allow-wildcard-cors: true

springdoc:
  swagger-ui:
    url: "static/api/spec.yaml"
  enable-default-api-docs: false
