spring.application.name: backend
server.port: ${port:9000}

spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: sapling-squad
    password: sapling-squad

appconfig:
  openapi:
    spec: "api/spec.yaml"
  allow-wildcard-cors: true
