spring.application.name: backend
server.port: ${port:9000}

spring:
  r2dbc:
    url: "r2dbc:postgresql://localhost/postgres"
    username: sapling-squad
    password: sapling-squad
appconfig:
  openapi:
    spec: "static/api/spec.yaml"
  allow-wildcard-cors: true

springdoc:
  swagger-ui:
    url: "static/api/spec.yaml"
  enable-default-api-docs: false
