ktor:
  application:
    modules:
      - saplingsquad.ApplicationKt.main
  deployment:
    port: 8080
  development: true

postgres:
  url: "r2dbc:postgresql://localhost/postgres"
  user: sapling-squad
  password: sapling-squad

openapi:
  spec: "api/spec.yaml"