ktor:
    application:
        modules:
            - saplingsquad.ApplicationKt.module
    deployment:
        port: 8080

postgres:
  url: "r2dbc:postgresql://localhost/postgres"
  user: sapling-squad
  password: sapling-squad