name: Backend

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'

defaults:
  run:
    working-directory: backend

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Install backend dependencies
        run: sbt clean compile

      - name: Run backend tests
        run: sbt test

  # Only runs on push to main
  deploy-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO
      - name: Deploy backend
        run: echo "TODO deploy backend here"
