name: Backend

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: backend

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/backend

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Test with Gradle # gradle build also tests
        run: ./gradlew build

  # Build always, tag `latest` only on `main`
  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: backend/Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  # Deploy only from main
  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Deploy
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ vars.DEPLOY_URL }}
          webhook_auth: ${{ secrets.DEPLOY_TOKEN }}
          webhook_auth_type: "bearer"
