name: Frontend

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'

defaults:
  run:
    working-directory: frontend

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      
      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test.unit -- --run

  # Only runs on push to main
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: test-frontend
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO
      - name: Deploy frontend
        run: echo "TODO deploy frontend here"
